"""Initial revision

Revision ID: 9ae70ebf975b
Revises: 
Create Date: 2025-12-04 12:28:29.048267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae70ebf975b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abc_menu_menuitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=30), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('keywords', sa.String(length=100), nullable=True),
    sa.Column('meta_title', sa.String(length=300), nullable=True, comment='Заголовок вкладки браузера и в поисковой выдаче'),
    sa.Column('h1', sa.String(length=300), nullable=True, comment='Главный заголовок на странице (должен отличаться от Title)'),
    sa.Column('text', sa.Text(), nullable=True, comment='Содержимое метки, Текст-статья (500-1500 символов) с естественным вхождением ключевых слов'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abc_menu_menuitem_url'), 'abc_menu_menuitem', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abc_menu_menuitem_url'), table_name='abc_menu_menuitem')
    op.drop_table('abc_menu_menuitem')
    # ### end Alembic commands ###
